ESS.Web/Controllers/HomeController.cs
using ESS.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ESS.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ESS.Web/Controllers/SelfMonitoringController.cs
using ESS.Data.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace ESS.Web.Controllers
{
    [Authorize]
    public class SelfMonitoringController : Controller
    {
        private readonly IConfiguration _config;
        private UserModel _user;
        public SelfMonitoringController(IConfiguration config)
        {
            _config = config;
        }
        public async Task<IActionResult> Index()
        {
            _user = UserModel.MappingFromAuth(User);
            string API_URI = _config.GetValue<string>("AppSettings:API_URI");
            var items = new List<SelfMonitoringViewModel>();
            var Vaccines = new List<VaccineModel>();

            Dictionary<string, string> dicChartData = new Dictionary<string, string>();
            var _listSuhuTubuh = new StringBuilder();
            var _listNoData = new StringBuilder();
            var _listSoreThroat = new StringBuilder();
            var _listFlu = new StringBuilder();
            var _listFever = new StringBuilder();
            var _listCough = new StringBuilder();
            var _listShortness = new StringBuilder();
            var _listSmellDisturbance = new StringBuilder();
            var _listTasteInterference = new StringBuilder();


            var _listIsDiarrhea = new StringBuilder();
            var _listIsSorePain = new StringBuilder();
            var _listIsJointPain = new StringBuilder();
            var _listIsDizzy = new StringBuilder();
            var _listIsHeadache = new StringBuilder();
            var _listIsTired = new StringBuilder();
            var _listIsShivering = new StringBuilder();
            var _listIsNausea = new StringBuilder();
            var _listIsGag = new StringBuilder();

            



            var _listContactPatient = new StringBuilder();
            var _listQuarantine = new StringBuilder();

            using (HttpClient client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _user.Token);
                string endpoint = API_URI + "/api/self/list";

                using (var Response = await client.GetAsync(endpoint))
                {
                    if (Response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var responseContent = Response.Content.ReadAsStringAsync();
                        items = JsonConvert.DeserializeObject<List<SelfMonitoringViewModel>>(responseContent.Result);                        

                        #region Data Chart
                        _listSuhuTubuh.AppendLine("[");
                        foreach (var item in items.OrderBy(x => x.DateTimeCheckIn))
                        {
                            _listSuhuTubuh.Append("{");
                            _listSuhuTubuh.Append(string.Format(" x: new Date({0}, {1}, {2}), y: {3} "
                                , item.DateTimeCheckIn.Year
                                , (item.DateTimeCheckIn.Month-1).ToString("00")
                                , (item.DateTimeCheckIn.Day).ToString("00")
                                , (item.BodyTemperatureNight > 0 ? item.BodyTemperatureNight : item.BodyTemperatureMorning)));
                            _listSuhuTubuh.Append("},");
                            _listSuhuTubuh.AppendLine("");
                        }
                        _listSuhuTubuh.AppendLine("]");


                        _listNoData.AppendLine("[");
                        foreach (var item in items.OrderBy(x => x.DateTimeCheckIn))
                        {
                            _listNoData.Append("{");
                            _listNoData.Append(string.Format(" x: new Date({0}, {1}, {2}), y: {3} "
                                , item.DateTimeCheckIn.Year
                                , (item.DateTimeCheckIn.Month-1).ToString("00")
                                , (item.DateTimeCheckIn.Day).ToString("00")
                                , (item.IsCheckIn ? 0 : 10)));
                            _listNoData.Append("},");
                            _listNoData.AppendLine("");
                        }
                        _listNoData.AppendLine("]");




                        _listSoreThroat.AppendLine("[");
                        foreach (var item in items.OrderBy(x => x.DateTimeCheckIn))
                        {
                            _listSoreThroat.Append("{");
                            _listSoreThroat.Append(string.Format(" x: new Date({0}, {1}, {2}), y: {3} "
                                , item.DateTimeCheckIn.Year
                                , (item.DateTimeCheckIn.Month-1).ToString("00")
                                , (item.DateTimeCheckIn.Day).ToString("00")
                                , (item.IsSoreThroat ? 10 : 0)));
                            _listSoreThroat.Append("},");
                            _listSoreThroat.AppendLine("");
                        }
                        _listSoreThroat.AppendLine("]");



                        //IS FLU
                        _listFlu.AppendLine("[");
                        foreach (var item in items.OrderBy(x => x.DateTimeCheckIn))
                        {
                            _listFlu.Append("{");
                            _listFlu.Append(string.Format(" x: new Date({0}, {1}, {2}), y: {3} "
                                , item.DateTimeCheckIn.Year
                                , (item.DateTimeCheckIn.Month-1).ToString("00")
                                , (item.DateTimeCheckIn.Day).ToString("00")
                                , (item.IsFlu ? 10 : 0)));
                            _listFlu.Append("},");
                            _listFlu.AppendLine("");
                        }
                        _listFlu.AppendLine("]");


                        // Is Fever
                        _listFever.AppendLine("[");
                        foreach (var item in items.OrderBy(x => x.DateTimeCheckIn))
                        {
                            _listFever.Append("{");
                            _listFever.Append(string.Format(" x: new Date({0}, {1}, {2}), y: {3} "
                                , item.DateTimeCheckIn.Year
                                , (item.DateTimeCheckIn.Month-1).ToString("00")
                                , (item.DateTimeCheckIn.Day).ToString("00")
                                , (item.IsFever ? 10 : 0)));
                            _listFever.Append("},");
                            _listFever.AppendLine("");
                        }
                        _listFever.AppendLine("]");


                        // Cough
                        _listCough.AppendLine("[");
                        foreach (var item in items.OrderBy(x => x.DateTimeCheckIn))
                        {
                            _listCough.Append("{");
                            _listCough.Append(string.Format(" x: new Date({0}, {1}, {2}), y: {3} "
                                , item.DateTimeCheckIn.Year
                                , (item.DateTimeCheckIn.Month-1).ToString("00")
                                , (item.DateTimeCheckIn.Day).ToString("00")
                                , (item.IsCough ? 10 : 0)));
                            _listCough.Append("},");
                            _listCough.AppendLine("");
                        }
                        _listCough.AppendLine("]");


                        // Shortness
                        _listShortness.AppendLine("[");
                        foreach (var item in items.OrderBy(x => x.DateTimeCheckIn))
                        {
                            _listShortness.Append("{");
                            _listShortness.Append(string.Format(" x: new Date({0}, {1}, {2}), y: {3} "
                                , item.DateTimeCheckIn.Year
                                , (item.DateTimeCheckIn.Month-1).ToString("00")
                                , (item.DateTimeCheckIn.Day).ToString("00")
                                , (item.IsShortness ? 10 : 0)));
                            _listShortness.Append("},");
                            _listShortness.AppendLine("");
                        }
                        _listShortness.AppendLine("]");

                        // Smell Disturbance
                        _listSmellDisturbance.AppendLine("[");
                        foreach (var item in items.OrderBy(x => x.DateTimeCheckIn))
                        {
                            _listSmellDisturbance.Append("{");
                            _listSmellDisturbance.Append(string.Format(" x: new Date({0}, {1}, {2}), y: {3} "
                                , item.DateTimeCheckIn.Year
                                , (item.DateTimeCheckIn.Month - 1).ToString("00")
                                , (item.DateTimeCheckIn.Day).ToString("00")
                                , (item.IsSmellDisturbance ? 10 : 0)));
                            _listSmellDisturbance.Append("},");
                            _listSmellDisturbance.AppendLine("");
                        }
                        _listSmellDisturbance.AppendLine("]");

                        // Taste Interference
                        _listTasteInterference.AppendLine("[");
                        foreach (var item in items.OrderBy(x => x.DateTimeCheckIn))
                        {
                            _listTasteInterference.Append("{");
                            _listTasteInterference.Append(string.Format(" x: new Date({0}, {1}, {2}), y: {3} "
                                , item.DateTimeCheckIn.Year

ESS.Web/Views/Home/Index.cshtml
@using ESS.Data.Model
 
@{
    ViewData["Title"] = "Home Page";
    UserModel UserModel = UserModel.MappingFromAuth(User);
}

<!--begin::Card-->
<div class="card card-custom gutter-b">
    <div class="card-body">
        <!--begin::Details-->
        <div class="d-flex">
            <!--begin: Pic-->
            <div class="flex-shrink-0 mr-4 mt-lg-0 mt-3">
                <div class="symbol symbol-80 symbol-lg-80">
                    <img src="~/assets/media/users/default.jpg" alt="image" />
                </div>
                <div class="symbol symbol-50 symbol-lg-80 symbol-primary d-none">
                    <span class="font-size-h3 symbol-label font-weight-boldest">JM</span>
                </div>
            </div>
            <!--end::Pic-->
            <!--begin::Info-->
            <div class="flex-grow-1">
                <!--begin::Title-->
                <div class="d-flex justify-content-between flex-wrap mt-1">
                    <div class="d-flex mr-3">
                        <a href="#" class="text-dark-75 text-hover-primary font-size-h5 font-weight-bold mr-3">@UserModel.FullName</a>
                    </div>
                </div>
                <!--end::Title-->
                <!--begin::Content-->
                <div class="d-flex flex-wrap justify-content-between mt-1">
                    <div class="d-flex flex-column flex-grow-1">
                        <div class="d-flex flex-wrap mb-4">
                            <a href="#" class="text-dark-50 text-hover-primary font-weight-bold mr-lg-8 mr-5 mb-lg-0">
                                <i class="flaticon2-new-email mr-2 font-size-lg"></i>@UserModel.Email
                            </a>
                            <a href="#" class="text-dark-50 text-hover-primary font-weight-bold font-size-xs">
                                <i class="flaticon2-placeholder mr-2"></i>@UserModel.CompanyName
                            </a>
                            <a href="#" class="text-dark-50 text-hover-primary font-weight-bold mr-lg-8 mr-5 mb-lg-0 font-size-xs">
                                <i class="flaticon2-calendar-3 mr-2"></i>@UserModel.Role
                            </a>
                        </div>
                    </div>
                </div>
                <!--end::Content-->
            </div>
            <!--end::Info-->
        </div>
        <!--end::Details-->
        <div class="separator separator-solid"></div>
    </div>
</div>
<!--end::Card-->
<!--begin::Row-->
<div class="row">
    <div class="col-lg-12">
        <!--begin::Advance Table Widget 2-->
        <div class="card card-custom card-stretch gutter-b pb-3">
            <!--begin::Header-->
            <div class="card-header border-0 pt-5">
                <h3 class="card-title">
                    <span class="card-label font-weight-bolder text-dark">Main Menu</span>
                </h3>
            </div>
            <!--end::Header-->
            <div class="separator separator-solid"></div>



            <!--begin::Body-->
            <div class="card-body p-3 pt-3">
                <div class="row pt-3">
                    <a href="@Url.Action("CheckIn", "SelfMonitoring")" class="col-3 text-center">
                        <div class="btn btn-icon btn-light-warning btn-lg mb-2">
                            <i class="flaticon2-notepad"></i>
                        </div>
                        <p class="text-dark font-size-xs">Self Monitoring</p>
                    </a>
                    @*<div class="col text-center">
                        <div class="btn btn-icon btn-light-warning btn-lg mb-2">
                            <i class="flaticon2-notepad"></i>
                        </div>
                        <p class="text-dark font-size-sm">Self Monitoring</p>
                    </div>
                    <div class="col text-center">
                        <div class="btn btn-icon btn-light-warning btn-lg mb-2">
                            <i class="flaticon2-notepad"></i>
                        </div>
                        <p class="text-dark font-size-sm">Self Monitoring</p>
                    </div>
                    <div class="col text-center">
                        <div class="btn btn-icon btn-light-warning btn-lg mb-2">
                            <i class="flaticon2-notepad"></i>
                        </div>
                        <p class="text-dark font-size-sm">Self Monitoring</p>
                    </div>*@
                </div>
            </div>
            <!--end::Body-->
        </div>
        <!--end::Advance Table Widget 2-->
    </div>
</div>
<!--end::Row-->